# Generated by Django 4.2.2 on 2023-08-08 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('index', '0020_footer_earn_url_footer_service_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='footer_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
