# Generated by Django 4.2.2 on 2023-08-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_indexpage_footer_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='footer_logo',
        ),
    ]
