# Generated by Django 4.2.2 on 2023-08-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_remove_indexpage_footer_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexpage',
            old_name='header_image',
            new_name='why_choose_us_image',
        ),
    ]
